h1. Complex excerpt test{anchor:complexexcerpttest}

{toc}

h2. Lists{anchor:lists}

* A list
* Another item
# Enumerated
# List
h6. Definition:
List

h6. Definition2:
List


h2. Table{anchor:table}

||A||Table||
|With|some|
|cells|here|


h2. Misc{anchor:misc}

{code}
Literal block
{code}
h2. Admonitions{anchor:admonitions}

{note}This is a note. This is the second line of the note paragraph.

This is another paragaph in the note.
{note}

{warning}
This is a warning
{warning}

{note}
This is a note
{note}

{tip}
This is a tip
{tip}

{excerpt}
This is the first real standalone paragraph.{excerpt}

All other elements before influence the element_level count, so having them before the paragraph tests the code quite good.
