language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
matrix:
  allow_failures:
    - python: 3.7
    - python: 3.8
    - python: 3.9
addons:
  apt:
    packages:
    - colordiff
install: pip install docutils flake8
script:
  - ./run-tests.sh
  - flake8 .
