language: python
dist: bionic
sudo: false
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
matrix:
  allow_failures:
    - python: 3.4
    - python: 3.5
    - python: 3.10
  include:
    - python: 2.6
      dist: trusty
    - python: 3.2
      dist: trusty
    - python: 3.3
      dist: trusty
addons:
  apt:
    packages:
    - colordiff
install: pip install docutils flake8
script:
  - ./run-tests.sh
  - flake8 .
